### ISSUE TITLE
Dialogs seem to be broken

### ISSUE THREAD

**Issue by mskelton** [one-dark/buildkite-dark-theme#1]
From @DuBistKomisch

> FYI dialogs (at least the block/input step ones) seem to be broken, the body and translucent backdrop are both light.

**Comment by mskelton** [comment]
@DuBistKomisch Could you provide some more details?  I'm not seeing this behavior.

**Comment by DuBistKomisch** [comment]
@mskelton I'm not seeing it now either... perhaps my other computer has an out of date version of your theme, I'll confirm tonight.

**Comment by DuBistKomisch** [comment]
Sorry I've been on leave for a while so haven't ended up using BuildKite. Turns out my other computer was on 2.0.0 of the theme, so yeah false alarm, my bad!
