### ISSUE TITLE
Group step status element is not styled correctly

### ISSUE THREAD

**Issue by dbeg** [one-dark/buildkite-dark-theme#12]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/683086/205150550-8239f792-175b-465f-851c-c63fbde73b7c.png">

<img width="313" alt="image" src="https://user-images.githubusercontent.com/683086/205150662-5270ab03-1281-4cdc-968d-ee85b561687a.png">

**Comment by mskelton** [comment]
@dbeg I'm not seeing this issue anymore, could you test this again?

**Comment by dbeg** [comment]
> @dbeg I'm not seeing this issue anymore, could you test this again?

I did notice that there seems to be some state change as the individual group steps change status. I suspect the issue I'm seeing is during that specific point in time.

I'll see if I can reproduce and add more context to this issue.

**Comment by mskelton** [comment]
@dbeg Is this good to close?

**Comment by dbeg** [comment]
Yep, I haven't been able to successfully reproduce for a while now.
